#:schema node_modules/wrangler/config-schema.json
name = "aldjan-portfolio-dev"
type = "javascript"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
watch_paths = ["src/**/*.jsx", "src/**/*.css"]
